#!/bin/bash

echo "Compiling examplePrograms"
for f in ./{examplePrograms,tests}/*.spl
do
	../build/splang --show-input --show-stages "$@" $f | perl -pe 's/\e\[?.*?[\@-~]//g' > $f.txt
done

pdflatex "assignment2.tex" || exit 1
pdflatex "assignment2.tex"
